const LIST_LANGUAGE = ["en", "vi"];
const LIST_MODE_DARK_LIGHT = {
  DARK: 0,
  LIGHT: 1,
};

const SIZE_ICON_DEFAULT = "1.6rem";

const SIZE_DIVIDER_DEFAULT = "100%";

export {
  LIST_LANGUAGE,
  LIST_MODE_DARK_LIGHT,
  SIZE_ICON_DEFAULT,
  SIZE_DIVIDER_DEFAULT,
};
